### ISSUE TITLE
python VS java

### ISSUE THREAD

**Issue by ardeal** [PythonTra1nee/OPMS_v3#2]
你好，朋友，

我现在也想使用python做一点东西，可是，看到很多朋友说，做大型的web应用，还是java生态多、成熟。

并且，别人说，很多功能java能做到，而python做不到。

所以，我被吓住了，，，，不知道选择使用python还是java做大型的web系统。

就你的经验来看，你觉得，使用python行吗？

另外，我对python、DJango比较熟悉。
java+tomcat，只是简单的用过一些。

thanks

Ardeal

**Comment by PythonTra1nee** [comment]
python 在性能方面对于大并发量确实存在一些问题，处于解释器的原因，对于多线程的支持并不好，但是相对来说，一般需求还是能够满足的。大部分工作也还是能够胜任。Java 自然没得说，发展了这么多年，虽然不是最牛逼的语言，但是完整的生态，能够解决很多问题。现在市面上公司还是 Java 为主。两个的领域定位个人觉得是不一样的，这也是为啥我一般用 python 做运维工具的原因。如果你真的想做大型 web 应用，可以尝试下 go，这是现在很多公司转型的方向，另外如果你坚持 python，可以考虑 flask 或者 tornado 框架。
